const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./harness.cjs');
function setup(t){const h=harness(t);h.run(fs.readFileSync(path.join(__dirname,'../js/stok-guncellik.js'),'utf8'));h.run("const stockNow=new Date('2026-09-10T10:00:00Z')");return h;}
test('stock freshness uses the oldest existing/reserved date instead of the latest import',t=>{const h=setup(t);const s=h.run("stockFreshnessState(stockFreshnessFromRows([{depo:'mars',tip:'mevcut',adet:4,stok_tarihi:'2026-09-10'},{depo:'mars',tip:'ayrilmis',adet:1,stok_tarihi:'2026-09-05'}]),stockNow)");assert.equal(s.date,'2026-09-05');assert.equal(s.age,5);assert.equal(s.status,'stale');assert.equal(s.depots[0].mevcut,4);assert.equal(s.depots[0].ayrilmis,1);});
test('a missing reserved date prevents a dated existing row being described as current',t=>{const h=setup(t);h.run("const sf=stockFreshnessFromRows([{depo:'mars',tip:'mevcut',adet:4,stok_tarihi:'2026-09-10'},{depo:'mars',tip:'ayrilmis',adet:1,stok_tarihi:null}])");assert.equal(h.run('stockFreshnessState(sf,stockNow).status'),'unknown');assert.equal(h.run("stockFreshnessDepotDate(sf,'mars',stockNow)"),null);assert.match(h.run("stockFreshnessHTML({kod:'ABC',stockFreshness:sf},stockNow)"),/Tarihi eksik kayıt var/);});
test('zero inventory with a dated row is distinct from an absent warehouse/model record',t=>{const h=setup(t);const absent=h.run("stockFreshnessHTML({kod:'ABC',stockFreshness:stockFreshnessFromRows([])},stockNow)");assert.match(absent,/kayıt bulunamadı/);assert.doesNotMatch(absent,/mevcut 0/);const zero=h.run("stockFreshnessHTML({kod:'ABC',stockFreshness:stockFreshnessFromRows([{depo:'mars',tip:'mevcut',adet:0,stok_tarihi:'2026-09-10'}])},stockNow)");assert.match(zero,/10.09.2026 · bugün/);assert.match(zero,/mevcut 0/);assert.match(zero,/Horoz<\/b>: Bu ürün için stok kaydı yok/);});
test('stock age follows the Istanbul calendar day across the UTC date boundary',t=>{const h=setup(t);const s=h.run("stockFreshnessState(stockFreshnessFromRows([{depo:'mars',tip:'mevcut',adet:2,stok_tarihi:'2026-09-10'}]),new Date('2026-09-09T21:30:00Z'))");assert.equal(s.age,0);assert.equal(s.status,'dated');assert.equal(h.run("stockFreshnessToday(new Date('2026-09-09T20:59:00Z'))"),'2026-09-09');});
test('stale warnings preserve the three-day transport depot and seven-day own depot thresholds',t=>{const h=setup(t);const s=h.run("stockFreshnessState(stockFreshnessFromRows([{depo:'mars',adet:1,stok_tarihi:'2026-09-07'},{depo:'horoz',adet:1,stok_tarihi:'2026-09-06'},{depo:'kadikoy',adet:1,stok_tarihi:'2026-09-03'}]),stockNow)");assert.equal(s.depots[0].status,'dated');assert.equal(s.depots[1].status,'stale');assert.equal(s.depots[2].status,'dated');assert.equal(s.status,'stale');});
test('future and invalid calendar dates warn rather than look fresh; warehouse labels are escaped',t=>{const h=setup(t);h.run("profil.depo_adi='<img src=x onerror=alert(1)>';const sf=stockFreshnessFromRows([{depo:'mars',adet:1,stok_tarihi:'2026-09-11'},{depo:'horoz',adet:1,stok_tarihi:'2026-02-30'},{depo:'kadikoy',adet:1,stok_tarihi:'<script>alert(1)</script>'}])");const s=h.run('stockFreshnessState(sf,stockNow)');assert.equal(s.status,'invalid');assert.equal(s.depots[0].future,true);assert.equal(s.depots[1].invalid,true);const html=h.run("stockFreshnessHTML({kod:'ABC',stockFreshness:sf},stockNow)");assert.match(html,/İleri tarih var/);assert.match(html,/Geçersiz tarih var/);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<script>|<img/);});
test('unqueried/error state is not labelled zero stock or a fresh query timestamp',t=>{const h=setup(t);assert.equal(h.run('stockFreshnessFromRows(null)'),null);assert.equal(h.run("stockFreshnessHTML({kod:'',stockFreshness:null},stockNow)"),'');assert.match(h.run("stockFreshnessHTML({kod:'ABC',stockFreshness:null},stockNow)"),/bekleniyor/);const html=h.run("stockFreshnessHTML({kod:'ABC',stockFreshness:null,veriHata:'Stok sorgulanamadı'},stockNow)");assert.match(html,/doğrulanamadı/);assert.doesNotMatch(html,/bugün|mevcut 0/);});
test('stock date warnings do not mutate prices, quantities, or prevent saving an offer',async t=>{const h=setup(t);h.seed();h.run("quoteRows[0].stockFreshness=stockFreshnessFromRows([{depo:'mars',adet:8,stok_tarihi:'2020-01-01'}]);const stockBefore=JSON.stringify(quoteRows[0]);stockFreshnessHTML(quoteRows[0],stockNow)");assert.equal(h.run('JSON.stringify(quoteRows[0])===stockBefore'),true);h.respond({data:{id:'saved'},error:null});assert.equal(await h.run('saveQuote()'),true);assert.equal(h.run('lastTot.finalNakit'),10400);});
test('an empty stock query clears old dates and quantities without claiming stock is zero',async t=>{const h=setup(t);h.seed();h.w.__sb.rpc=async()=>({data:[{urun_adi:'Test ürün',toptan_fiyat:10000,bip_tutar:0,nakit_fiyat:14000}],error:null});h.respond({data:[],error:null});h.run("quoteRows[0].stockFreshness=stockFreshnessFromRows([{depo:'mars',adet:8,stok_tarihi:'2026-09-10'}]);quoteRows[0].kadikoyTarih='2026-09-10'");await h.run('refetch(quoteRows[0])');assert.equal(h.run('quoteRows[0].netStok'),null);assert.equal(h.run('quoteRows[0].marsMevcut'),null);assert.equal(h.run('quoteRows[0].kadikoyTarih'),null);assert.match(h.run("$('rows').textContent"),/mevcut kayıt bulunamadı/);assert.doesNotMatch(h.run("$('rows').textContent"),/KAYITLARDA STOK YOK/);h.respond({data:{id:'saved-empty-stock'},error:null});assert.equal(await h.run('saveQuote()'),true);});
test('standalone stock lookup distinguishes absent records from a stored zero count',async t=>{const h=setup(t);h.w.__sb.rpc=async()=>({data:[{urun_adi:'Test ürün',toptan_fiyat:10000}],error:null});h.run("$('stokSorguInput').value='TEST123'");h.respond({data:[],error:null});await h.run('stokSorgula()');const empty=h.run("$('stokSorguSonuc').textContent");assert.match(empty,/Mevcut stok kaydı yok/);assert.doesNotMatch(empty,/KULLANILABİLİR STOK YOK/);h.respond({data:[{depo:'mars',tip:'mevcut',adet:0,stok_tarihi:'2026-09-10'}],error:null});await h.run('stokSorgula()');const zero=h.run("$('stokSorguSonuc').textContent");assert.match(zero,/mevcut 0/);assert.match(zero,/KAYITLARA GÖRE KULLANILABİLİR STOK YOK/);});
test('late stock lookups cannot overwrite a newer search even for the same model',async t=>{const h=setup(t);let resolveFirst;const firstStock=new Promise(resolve=>{resolveFirst=resolve;});const rpcCalls=[];h.w.__sb.rpc=async(name,args)=>{rpcCalls.push({name,args});return {data:[{urun_adi:'Test ürün',toptan_fiyat:10000}],error:null};};h.run("$('stokSorguInput').value='TEST123'");h.respond(firstStock);const first=h.run('stokSorgula()');await new Promise(setImmediate);assert.equal(h.calls.length,1);h.respond({data:[{depo:'mars',adet:2,stok_tarihi:'2026-09-10'}],error:null});await h.run('stokSorgula()');const latest=h.run("$('stokSorguSonuc').innerHTML");resolveFirst({data:[{depo:'mars',adet:99,stok_tarihi:'2020-01-01'}],error:null});await first;assert.equal(h.run("$('stokSorguSonuc').innerHTML"),latest);assert.equal(rpcCalls[0].args.p_marka,'bosch');assert.ok(h.calls[0].methods.some(m=>m[0]==='eq'&&m[1]==='marka'&&m[2]==='bosch'));assert.ok(h.calls[0].methods.some(m=>m[0]==='eq'&&m[1]==='bayi_id'&&m[2]==='central'));});
test('late price/stock replies are ignored after brand, account, owner, epoch, or search changes',async t=>{const changes=["brand='siemens'","authUid='user-b'","profil.bayi_sahibi='other-owner'","fqEpoch++","$('stokSorguInput').value='OTHER123'","stokSorguKapat()"];
 for(const stage of ['price','stock'])for(const change of changes){const h=setup(t);let resolveReply;const delayed=new Promise(resolve=>{resolveReply=resolve;});h.run("$('stokSorguInput').value='TEST123'");h.w.__sb.rpc=async()=>stage==='price'?delayed:{data:[{urun_adi:'OLD RESULT',toptan_fiyat:10000}],error:null};h.respond(stage==='stock'?delayed:{data:[],error:null});const pending=h.run('stokSorgula()');await new Promise(setImmediate);h.run(change+";$('stokSorguSonuc').textContent='NEW SCREEN'");resolveReply(stage==='price'?{data:[{urun_adi:'OLD RESULT',toptan_fiyat:10000}],error:null}:{data:[{depo:'mars',adet:99,stok_tarihi:'2026-09-10'}],error:null});await pending;assert.equal(h.run("$('stokSorguSonuc').textContent"),'NEW SCREEN',stage+' '+change);if(stage==='price')assert.equal(h.calls.length,0);}
});
